name: Reusable Release Worker

on:
  workflow_call:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      RELEASE_FILES: >
        src/
        LICENSE
        README.md
        README.zh-TW.md
        ci.sh
        docker-compose.yaml
        cov-tui.py
      VERSION: "${{ github.ref_name }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Package project
        run: |
          tar -czvf bats-helper-${VERSION}.tar.gz ${RELEASE_FILES}
          zip -r bats-helper-${VERSION}.zip ${RELEASE_FILES}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bats-helper-${{ github.ref_name }}.tar.gz
            bats-helper-${{ github.ref_name }}.zip
          # 自動生成 Release Note (從 Commit 紀錄)
          generate_release_notes: true
          prerelease: "${{ contains(github.ref_name, '-') }}"
